/* Generated by tools/gen-shader-strings.py -- do not edit.

   The shader picker's labels, descriptions and caveats are data, read at
   runtime from shaders/manifest.json. tools/i18n-extract.py scans only this
   repo's sources, so without this mirror those strings reach no .pot and no
   translator can find them. JW_UI() is a no-op marker the extractor already
   recognises; the picker calls T() on the manifest's own value at draw time and
   the lookup matches because the text is identical.

   Nothing reads this table at runtime -- it exists to be extracted. It is not
   static so an unused-variable warning cannot fire on a warning-free build. */

#include "internal/i18n/i18n.h"

const char *const kShaderCatalogStrings[] = {
    JW_UI("Sharp Pixels"),
    JW_UI("Keeps pixel art crisp at integer and non-integer scaling without adding a CRT effect."),
    JW_UI("This is a scaling filter, not a CRT simulation."),
    JW_UI("120Hz cadence counters can report periodic drops for nominal 59.94/60fps content."),
    JW_UI("Subtle Scanlines"),
    JW_UI("Adds lightweight scanlines with reduced darkness for 8-bit, 16-bit, and PlayStation-era games."),
    JW_UI("Best at integer or near-integer scaling; the upstream shader can look uneven at arbitrary scales."),
    JW_UI("Scanlines reduce brightness, especially when combined with BFI."),
    JW_UI("GBA Color"),
    JW_UI("Tames colors authored for the original Game Boy Advance LCD."),
    JW_UI("Use only for GBA content."),
    JW_UI("Do not combine with BFI when using mGBA: the no-shader mGBA control falls to 38.499 FPS at 120Hz with BFI."),
    JW_UI("GBC Color"),
    JW_UI("Approximates the softer color response of the Game Boy Color LCD."),
    JW_UI("Use only for Game Boy Color content."),
    JW_UI("BFI further reduces brightness."),
    JW_UI("Game Boy LCD"),
    JW_UI("Adds a subdued Pocket-style backing texture, pixel grid, and edge shadows for original Game Boy games."),
    JW_UI("Use only for original Game Boy content."),
    JW_UI("The texture and grid intentionally soften bright flat colors."),
    JW_UI("120Hz BFI measured 59.249 FPS and further reduces brightness."),
    JW_UI("Game Boy Color LCD"),
    JW_UI("Adds a Pocket-style backing texture and low-cost pixel grid tuned for Game Boy Color art."),
    JW_UI("This is a stronger display simulation than the simpler GBC Color preset."),
    JW_UI("Game Boy Advance LCD"),
    JW_UI("Adds a gray backing texture, low-cost pixel grid, and transparency response tuned for the original GBA screen."),
    JW_UI("Use only for original Game Boy Advance content."),
    JW_UI("Keep mGBA BFI off: the no-shader core path already falls below full speed at 120Hz with BFI."),
    JW_UI("Sharp Shimmerless"),
    JW_UI("Keeps rectangular pixels as sharp as possible at awkward non-integer scales while avoiding scrolling shimmer."),
    JW_UI("Prefer this over Sharp Pixels when non-integer scrolling visibly shimmers."),
    JW_UI("It is a scaling filter, not a CRT or LCD simulation."),
    JW_UI("CRT Lite"),
    JW_UI("Adds a lightweight aperture mask and softened scanlines without curvature."),
    JW_UI("Keep BFI off: PS1 at 120Hz with BFI measured 50.282 FPS."),
    JW_UI("CRT effects reduce brightness; the preset uses a milder mask and scanline strength than upstream defaults."),
    JW_UI("LCD Grid"),
    JW_UI("Adds the fine RGB pixel grid of a handheld LCD panel."),
    JW_UI("Designed for handheld content; the grid is very fine at console resolutions."),
    JW_UI("120Hz cadence counters can report periodic drops for nominal 60fps content."),
    JW_UI("LCD Grid Fast"),
    JW_UI("A lighter handheld LCD grid with softer cell edges."),
    JW_UI("Designed for handheld content."),
    JW_UI("CRT Sharp"),
    JW_UI("Scanlines and an aperture mask with a flat screen and crisp scaling."),
    JW_UI("No screen curvature; use CRT Curved for that."),
    JW_UI("CRT Curved"),
    JW_UI("Scanlines and aperture mask with screen curvature, rounded corners and vignetting."),
    JW_UI("Curvature crops slightly at the screen edges."),
    JW_UI("Carries a Leaf local patch until upstream fixes its GLSL ES precision mismatch."),
};

const int kShaderCatalogStringCount =
    (int)(sizeof(kShaderCatalogStrings) / sizeof(kShaderCatalogStrings[0]));
