#!/usr/bin/env python3
"""Mirror the shader catalog's UI strings into a C table the extractor can see.

The shader picker's row labels, descriptions and caveats are not written in C:
they are data, loaded at runtime from the assembled shaders/manifest.json whose
source of truth lives in a sibling repo (retroarch-builds). tools/i18n-extract.py
only scans Jawaka's own sources, and the i18n CI job checks out Jawaka alone, so
those strings reached no .pot and no translator could find them -- which is
exactly how the Spanish translator hit a Shaders page still in English.

Rather than teach the extractor to read another repo it cannot count on being
there, the strings are mirrored here as JW_UI() markers. JW_UI is a no-op that
the extractor already recognises anywhere in a scanned source, so the generated
table needs no extractor change and no build-time dependency. At runtime the
picker calls T() on the value it read from the manifest; the lookup matches
because the msgid text is identical.

The table is generated, never hand-edited. Run --check in the workspace to catch
drift after the catalog changes; it no-ops where the sibling repo is absent, so
a Jawaka-only checkout is not blocked by a repo it cannot see.

    tools/gen-shader-strings.py            # rewrite the table
    tools/gen-shader-strings.py --check    # fail if it is stale
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "internal/retroarch/shader_strings.c"
CATALOG = ROOT.parent / "retroarch-builds/shader-sources/mlp1-recommended.json"

HEADER = """/* Generated by tools/gen-shader-strings.py -- do not edit.

   The shader picker's labels, descriptions and caveats are data, read at
   runtime from shaders/manifest.json. tools/i18n-extract.py scans only this
   repo's sources, so without this mirror those strings reach no .pot and no
   translator can find them. JW_UI() is a no-op marker the extractor already
   recognises; the picker calls T() on the manifest's own value at draw time and
   the lookup matches because the text is identical.

   Nothing reads this table at runtime -- it exists to be extracted. It is not
   static so an unused-variable warning cannot fire on a warning-free build. */

#include "internal/i18n/i18n.h"

const char *const kShaderCatalogStrings[] = {
"""

FOOTER = """};

const int kShaderCatalogStringCount =
    (int)(sizeof(kShaderCatalogStrings) / sizeof(kShaderCatalogStrings[0]));
"""


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def collect(catalog: Path) -> list[str]:
    """Every user-visible string in the catalog, in catalog order, deduped.

    Order follows the file rather than sorting, so a diff of the generated table
    reads as the catalog's own diff."""
    data = json.loads(catalog.read_text())
    out: list[str] = []
    seen: set[str] = set()

    def add(value):
        if isinstance(value, str) and value.strip() and value not in seen:
            seen.add(value)
            out.append(value)

    for preset in data.get("presets", []):
        add(preset.get("display_name"))
        add(preset.get("description"))
        for constraint in preset.get("constraints", []) or []:
            add(constraint)
    return out


def render(strings: list[str]) -> str:
    body = "".join(f'    JW_UI("{c_escape(s)}"),\n' for s in strings)
    return HEADER + body + FOOTER


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed table is stale")
    args = ap.parse_args()

    if not CATALOG.exists():
        # A Jawaka-only checkout (the i18n CI job is one) cannot see the sibling
        # repo. Skipping is deliberate: the committed table is what the .pot is
        # built from, so nothing is silently dropped by not regenerating here.
        print(f"shader catalog not present ({CATALOG}); skipping", file=sys.stderr)
        return 0

    text = render(collect(CATALOG))
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is stale; run tools/gen-shader-strings.py",
                  file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} is current")
        return 0

    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(collect(CATALOG))} strings)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
